# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.v1alpha1.org.businesshours import entities_pb2 as api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2


class BusinessHoursServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListBusinessHours = channel.unary_unary(
                '/api.v1alpha1.org.businesshours.BusinessHoursService/ListBusinessHours',
                request_serializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.ListBusinessHoursRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.ListBusinessHoursResponse.FromString,
                )
        self.GetBusinessHours = channel.unary_unary(
                '/api.v1alpha1.org.businesshours.BusinessHoursService/GetBusinessHours',
                request_serializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.GetBusinessHoursRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.GetBusinessHoursResponse.FromString,
                )
        self.SetBusinessHours = channel.unary_unary(
                '/api.v1alpha1.org.businesshours.BusinessHoursService/SetBusinessHours',
                request_serializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.SetBusinessHoursRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.SetBusinessHoursResponse.FromString,
                )
        self.AddIntervalToBusinessHours = channel.unary_unary(
                '/api.v1alpha1.org.businesshours.BusinessHoursService/AddIntervalToBusinessHours',
                request_serializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.AddIntervalToBusinessHoursRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.AddIntervalToBusinessHoursResponse.FromString,
                )
        self.RemoveIntervalFromBusinessHours = channel.unary_unary(
                '/api.v1alpha1.org.businesshours.BusinessHoursService/RemoveIntervalFromBusinessHours',
                request_serializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.RemoveIntervalFromBusinessHoursRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.RemoveIntervalFromBusinessHoursResponse.FromString,
                )
        self.UpdateBusinessHoursInfo = channel.unary_unary(
                '/api.v1alpha1.org.businesshours.BusinessHoursService/UpdateBusinessHoursInfo',
                request_serializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.UpdateBusinessHoursInfoRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.UpdateBusinessHoursInfoResponse.FromString,
                )
        self.DeleteBusinessHours = channel.unary_unary(
                '/api.v1alpha1.org.businesshours.BusinessHoursService/DeleteBusinessHours',
                request_serializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.DeleteBusinessHoursRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.DeleteBusinessHoursResponse.FromString,
                )
        self.EvaluateBusinessHours = channel.unary_unary(
                '/api.v1alpha1.org.businesshours.BusinessHoursService/EvaluateBusinessHours',
                request_serializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.EvaluateBusinessHoursRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.EvaluateBusinessHoursResponse.FromString,
                )


class BusinessHoursServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListBusinessHours(self, request, context):
        """ListBusinessHours returns all business hours for an Org.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBusinessHours(self, request, context):
        """GetBusinessHours returns the business hours for the ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBusinessHours(self, request, context):
        """SetBusinessHours initializes a business hours object
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddIntervalToBusinessHours(self, request, context):
        """AddIntervalToBusinessHours adds a day interval to a business hours object
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveIntervalFromBusinessHours(self, request, context):
        """RemoveIntervalFromBusinessHours removes a day interval from a business hours object
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBusinessHoursInfo(self, request, context):
        """UpdateBusinessHoursInfo updates the general info of a business hours object
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBusinessHours(self, request, context):
        """DeleteBusinessHours removes business hours.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateBusinessHours(self, request, context):
        """EvaluateBusinessHours determines whether or not the current time is within a business hours day interval
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BusinessHoursServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListBusinessHours': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBusinessHours,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.ListBusinessHoursRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.ListBusinessHoursResponse.SerializeToString,
            ),
            'GetBusinessHours': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBusinessHours,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.GetBusinessHoursRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.GetBusinessHoursResponse.SerializeToString,
            ),
            'SetBusinessHours': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBusinessHours,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.SetBusinessHoursRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.SetBusinessHoursResponse.SerializeToString,
            ),
            'AddIntervalToBusinessHours': grpc.unary_unary_rpc_method_handler(
                    servicer.AddIntervalToBusinessHours,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.AddIntervalToBusinessHoursRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.AddIntervalToBusinessHoursResponse.SerializeToString,
            ),
            'RemoveIntervalFromBusinessHours': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveIntervalFromBusinessHours,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.RemoveIntervalFromBusinessHoursRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.RemoveIntervalFromBusinessHoursResponse.SerializeToString,
            ),
            'UpdateBusinessHoursInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBusinessHoursInfo,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.UpdateBusinessHoursInfoRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.UpdateBusinessHoursInfoResponse.SerializeToString,
            ),
            'DeleteBusinessHours': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBusinessHours,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.DeleteBusinessHoursRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.DeleteBusinessHoursResponse.SerializeToString,
            ),
            'EvaluateBusinessHours': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateBusinessHours,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.EvaluateBusinessHoursRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.EvaluateBusinessHoursResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1alpha1.org.businesshours.BusinessHoursService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BusinessHoursService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListBusinessHours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.org.businesshours.BusinessHoursService/ListBusinessHours',
            api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.ListBusinessHoursRequest.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.ListBusinessHoursResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBusinessHours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.org.businesshours.BusinessHoursService/GetBusinessHours',
            api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.GetBusinessHoursRequest.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.GetBusinessHoursResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetBusinessHours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.org.businesshours.BusinessHoursService/SetBusinessHours',
            api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.SetBusinessHoursRequest.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.SetBusinessHoursResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddIntervalToBusinessHours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.org.businesshours.BusinessHoursService/AddIntervalToBusinessHours',
            api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.AddIntervalToBusinessHoursRequest.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.AddIntervalToBusinessHoursResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveIntervalFromBusinessHours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.org.businesshours.BusinessHoursService/RemoveIntervalFromBusinessHours',
            api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.RemoveIntervalFromBusinessHoursRequest.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.RemoveIntervalFromBusinessHoursResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateBusinessHoursInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.org.businesshours.BusinessHoursService/UpdateBusinessHoursInfo',
            api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.UpdateBusinessHoursInfoRequest.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.UpdateBusinessHoursInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteBusinessHours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.org.businesshours.BusinessHoursService/DeleteBusinessHours',
            api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.DeleteBusinessHoursRequest.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.DeleteBusinessHoursResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EvaluateBusinessHours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.org.businesshours.BusinessHoursService/EvaluateBusinessHours',
            api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.EvaluateBusinessHoursRequest.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_businesshours_dot_entities__pb2.EvaluateBusinessHoursResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
