# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/translations/v1alpha1/entities.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'services/translations/v1alpha1/entities.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-services/translations/v1alpha1/entities.proto\x12\x1eservices.translations.v1alpha1\"P\n\x18TranslateTemplateRequest\x12\x1a\n\x08template\x18\x01 \x01(\tR\x08template\x12\x18\n\x07\x63ontext\x18\x02 \x01(\tR\x07\x63ontext\"l\n\x19TranslateTemplateResponse\x12O\n\x0ctranslations\x18\x01 \x03(\x0b\x32+.services.translations.v1alpha1.TranslationR\x0ctranslations\"\xe5\x01\n\x0bTranslation\x12%\n\x0etranslation_id\x18\x01 \x01(\tR\rtranslationId\x12\x1a\n\x08template\x18\x02 \x01(\tR\x08template\x12\x18\n\x07\x63ontext\x18\x03 \x01(\tR\x07\x63ontext\x12!\n\x0clanguage_tag\x18\x04 \x01(\tR\x0blanguageTag\x12\'\n\x0fllm_translation\x18\x05 \x01(\tR\x0ellmTranslation\x12-\n\x12manual_translation\x18\x06 \x01(\tR\x11manualTranslationB\xcd\x01\n\"com.services.translations.v1alpha1B\rEntitiesProtoP\x01\xa2\x02\x03STX\xaa\x02\x1eServices.Translations.V1alpha1\xca\x02\x1eServices\\Translations\\V1alpha1\xe2\x02*Services\\Translations\\V1alpha1\\GPBMetadata\xea\x02 Services::Translations::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.translations.v1alpha1.entities_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"com.services.translations.v1alpha1B\rEntitiesProtoP\001\242\002\003STX\252\002\036Services.Translations.V1alpha1\312\002\036Services\\Translations\\V1alpha1\342\002*Services\\Translations\\V1alpha1\\GPBMetadata\352\002 Services::Translations::V1alpha1'
  _globals['_TRANSLATETEMPLATEREQUEST']._serialized_start=81
  _globals['_TRANSLATETEMPLATEREQUEST']._serialized_end=161
  _globals['_TRANSLATETEMPLATERESPONSE']._serialized_start=163
  _globals['_TRANSLATETEMPLATERESPONSE']._serialized_end=271
  _globals['_TRANSLATION']._serialized_start=274
  _globals['_TRANSLATION']._serialized_end=503
# @@protoc_insertion_point(module_scope)
