# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/billing/entities/v1alpha1/product.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0services/billing/entities/v1alpha1/product.proto\x12\"services.billing.entities.v1alpha1*\x98\x02\n\x07Product\x12\x17\n\x13PRODUCT_UNSPECIFIED\x10\x00\x12\x17\n\x13PRODUCT_AGENT_SEATS\x10\x64\x12\x18\n\x13PRODUCT_EMAILS_SENT\x10\xc8\x01\x12\x1c\n\x17PRODUCT_EMAILS_RECEIVED\x10\xc9\x01\x12\x15\n\x10PRODUCT_SMS_SENT\x10\xca\x01\x12\x19\n\x14PRODUCT_SMS_RECEIVED\x10\xcb\x01\x12\x16\n\x11PRODUCT_CHAT_SENT\x10\xcc\x01\x12\x1a\n\x15PRODUCT_CHAT_RECEIVED\x10\xcd\x01\x12\x11\n\x0cPRODUCT_OMNI\x10\xac\x02\x12\x11\n\x0cPRODUCT_VANA\x10\x90\x03\x12\x17\n\x12PRODUCT_COMPLIANCE\x10\xf4\x03\x42\xe1\x01\n&com.services.billing.entities.v1alpha1B\x0cProductProtoP\x01\xa2\x02\x03SBE\xaa\x02\"Services.Billing.Entities.V1alpha1\xca\x02\"Services\\Billing\\Entities\\V1alpha1\xe2\x02.Services\\Billing\\Entities\\V1alpha1\\GPBMetadata\xea\x02%Services::Billing::Entities::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.billing.entities.v1alpha1.product_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n&com.services.billing.entities.v1alpha1B\014ProductProtoP\001\242\002\003SBE\252\002\"Services.Billing.Entities.V1alpha1\312\002\"Services\\Billing\\Entities\\V1alpha1\342\002.Services\\Billing\\Entities\\V1alpha1\\GPBMetadata\352\002%Services::Billing::Entities::V1alpha1'
  _globals['_PRODUCT']._serialized_start=89
  _globals['_PRODUCT']._serialized_end=369
# @@protoc_insertion_point(module_scope)
