# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1alpha1/org/auth_connections.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.commons.org import auth_connections_pb2 as api_dot_commons_dot_org_dot_auth__connections__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'api/v1alpha1/org/auth_connections.proto\x12\x10\x61pi.v1alpha1.org\x1a&api/commons/org/auth_connections.proto\"\x87\x01\n\x1b\x43reateAuthConnectionRequest\x12\x43\n\x08settings\x18\x01 \x01(\x0b\x32\'.api.commons.org.AuthConnectionSettingsR\x08settings\x12#\n\rclient_secret\x18\x02 \x01(\tR\x0c\x63lientSecret\"\x1e\n\x1c\x43reateAuthConnectionResponse\"\"\n GetAuthConnectionSettingsRequest\"h\n!GetAuthConnectionSettingsResponse\x12\x43\n\x08settings\x18\x01 \x01(\x0b\x32\'.api.commons.org.AuthConnectionSettingsR\x08settings\"B\n\x1b\x44\x65leteAuthConnectionRequest\x12#\n\rconnection_id\x18\x01 \x01(\tR\x0c\x63onnectionId\"\x1e\n\x1c\x44\x65leteAuthConnectionResponse\"m\n!UpdateAuthConnectionSecretRequest\x12#\n\rconnection_id\x18\x01 \x01(\tR\x0c\x63onnectionId\x12#\n\rclient_secret\x18\x02 \x01(\tR\x0c\x63lientSecret\"$\n\"UpdateAuthConnectionSecretResponse\"\xa5\x01\n!UpdateAuthConnectionGroupsRequest\x12?\n\rdefault_group\x18\x01 \x01(\x0b\x32\x1a.api.commons.org.GroupItemR\x0c\x64\x65\x66\x61ultGroup\x12?\n\rcustom_groups\x18\x02 \x03(\x0b\x32\x1a.api.commons.org.GroupItemR\x0c\x63ustomGroups\"$\n\"UpdateAuthConnectionGroupsResponseB\x8e\x01\n\x14\x63om.api.v1alpha1.orgB\x14\x41uthConnectionsProtoP\x01\xa2\x02\x03\x41VO\xaa\x02\x10\x41pi.V1alpha1.Org\xca\x02\x10\x41pi\\V1alpha1\\Org\xe2\x02\x1c\x41pi\\V1alpha1\\Org\\GPBMetadata\xea\x02\x12\x41pi::V1alpha1::Orgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1alpha1.org.auth_connections_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024com.api.v1alpha1.orgB\024AuthConnectionsProtoP\001\242\002\003AVO\252\002\020Api.V1alpha1.Org\312\002\020Api\\V1alpha1\\Org\342\002\034Api\\V1alpha1\\Org\\GPBMetadata\352\002\022Api::V1alpha1::Org'
  _globals['_CREATEAUTHCONNECTIONREQUEST']._serialized_start=102
  _globals['_CREATEAUTHCONNECTIONREQUEST']._serialized_end=237
  _globals['_CREATEAUTHCONNECTIONRESPONSE']._serialized_start=239
  _globals['_CREATEAUTHCONNECTIONRESPONSE']._serialized_end=269
  _globals['_GETAUTHCONNECTIONSETTINGSREQUEST']._serialized_start=271
  _globals['_GETAUTHCONNECTIONSETTINGSREQUEST']._serialized_end=305
  _globals['_GETAUTHCONNECTIONSETTINGSRESPONSE']._serialized_start=307
  _globals['_GETAUTHCONNECTIONSETTINGSRESPONSE']._serialized_end=411
  _globals['_DELETEAUTHCONNECTIONREQUEST']._serialized_start=413
  _globals['_DELETEAUTHCONNECTIONREQUEST']._serialized_end=479
  _globals['_DELETEAUTHCONNECTIONRESPONSE']._serialized_start=481
  _globals['_DELETEAUTHCONNECTIONRESPONSE']._serialized_end=511
  _globals['_UPDATEAUTHCONNECTIONSECRETREQUEST']._serialized_start=513
  _globals['_UPDATEAUTHCONNECTIONSECRETREQUEST']._serialized_end=622
  _globals['_UPDATEAUTHCONNECTIONSECRETRESPONSE']._serialized_start=624
  _globals['_UPDATEAUTHCONNECTIONSECRETRESPONSE']._serialized_end=660
  _globals['_UPDATEAUTHCONNECTIONGROUPSREQUEST']._serialized_start=663
  _globals['_UPDATEAUTHCONNECTIONGROUPSREQUEST']._serialized_end=828
  _globals['_UPDATEAUTHCONNECTIONGROUPSRESPONSE']._serialized_start=830
  _globals['_UPDATEAUTHCONNECTIONGROUPSRESPONSE']._serialized_end=866
# @@protoc_insertion_point(module_scope)
