# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wfo/vanalytics/v2/dncl_list.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'wfo/vanalytics/v2/dncl_list.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.commons import compliance_pb2 as api_dot_commons_dot_compliance__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!wfo/vanalytics/v2/dncl_list.proto\x12\x11wfo.vanalytics.v2\x1a\x1c\x61pi/commons/compliance.proto\"\xfd\x01\n\x08\x44nclList\x12\x17\n\x07list_id\x18\x02 \x01(\tR\x06listId\x12;\n\x0c\x63ontent_type\x18\x03 \x01(\x0e\x32\x18.api.commons.ContentTypeR\x0b\x63ontentType\x12H\n\rexpire_period\x18\x04 \x01(\x0e\x32#.wfo.vanalytics.v2.DnclExpirePeriodR\x0c\x65xpirePeriod\x12#\n\rexpire_offset\x18\x05 \x01(\x04R\x0c\x65xpireOffset\x12,\n\x12\x61gent_response_key\x18\x06 \x01(\tR\x10\x61gentResponseKey*\xa4\x01\n\x10\x44nclExpirePeriod\x12\x1b\n\x17\x44NCL_EXPIRE_PERIOD_HOUR\x10\x00\x12\x1a\n\x16\x44NCL_EXPIRE_PERIOD_DAY\x10\x01\x12\x1b\n\x17\x44NCL_EXPIRE_PERIOD_WEEK\x10\x02\x12\x1c\n\x18\x44NCL_EXPIRE_PERIOD_NEVER\x10\x03\x12\x1c\n\x18\x44NCL_EXPIRE_PERIOD_MONTH\x10\x04\x42\x8c\x01\n\x15\x63om.wfo.vanalytics.v2B\rDnclListProtoP\x01\xa2\x02\x03WVX\xaa\x02\x11Wfo.Vanalytics.V2\xca\x02\x11Wfo\\Vanalytics\\V2\xe2\x02\x1dWfo\\Vanalytics\\V2\\GPBMetadata\xea\x02\x13Wfo::Vanalytics::V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wfo.vanalytics.v2.dncl_list_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.wfo.vanalytics.v2B\rDnclListProtoP\001\242\002\003WVX\252\002\021Wfo.Vanalytics.V2\312\002\021Wfo\\Vanalytics\\V2\342\002\035Wfo\\Vanalytics\\V2\\GPBMetadata\352\002\023Wfo::Vanalytics::V2'
  _globals['_DNCLEXPIREPERIOD']._serialized_start=343
  _globals['_DNCLEXPIREPERIOD']._serialized_end=507
  _globals['_DNCLLIST']._serialized_start=87
  _globals['_DNCLLIST']._serialized_end=340
# @@protoc_insertion_point(module_scope)
