# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.v1alpha1.org.labels import entities_pb2 as api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2


class LabelsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateLabel = channel.unary_unary(
                '/api.v1alpha1.org.labels.LabelsService/CreateLabel',
                request_serializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.CreateLabelRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.CreateLabelResponse.FromString,
                )
        self.GetLabel = channel.unary_unary(
                '/api.v1alpha1.org.labels.LabelsService/GetLabel',
                request_serializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.GetLabelRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.GetLabelResponse.FromString,
                )
        self.UpdateLabel = channel.unary_unary(
                '/api.v1alpha1.org.labels.LabelsService/UpdateLabel',
                request_serializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.UpdateLabelRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.UpdateLabelResponse.FromString,
                )
        self.ListLabels = channel.unary_unary(
                '/api.v1alpha1.org.labels.LabelsService/ListLabels',
                request_serializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.ListLabelsRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.ListLabelsResponse.FromString,
                )
        self.DeleteLabel = channel.unary_unary(
                '/api.v1alpha1.org.labels.LabelsService/DeleteLabel',
                request_serializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.DeleteLabelRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.DeleteLabelResponse.FromString,
                )
        self.AttachLabel = channel.unary_unary(
                '/api.v1alpha1.org.labels.LabelsService/AttachLabel',
                request_serializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.AttachLabelRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.AttachLabelResponse.FromString,
                )
        self.DetachLabel = channel.unary_unary(
                '/api.v1alpha1.org.labels.LabelsService/DetachLabel',
                request_serializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.DetachLabelRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.DetachLabelResponse.FromString,
                )
        self.GetLabeledEntityMap = channel.unary_unary(
                '/api.v1alpha1.org.labels.LabelsService/GetLabeledEntityMap',
                request_serializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.GetLabeledEntityMapRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.GetLabeledEntityMapResponse.FromString,
                )
        self.AssignLabels = channel.unary_unary(
                '/api.v1alpha1.org.labels.LabelsService/AssignLabels',
                request_serializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.AssignLabelsRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.AssignLabelsResponse.FromString,
                )
        self.RevokeLabels = channel.unary_unary(
                '/api.v1alpha1.org.labels.LabelsService/RevokeLabels',
                request_serializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.RevokeLabelsRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.RevokeLabelsResponse.FromString,
                )


class LabelsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateLabel(self, request, context):
        """CreateLabel creates a new label.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLabel(self, request, context):
        """GetLabel gets a single label
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLabel(self, request, context):
        """UpdateLabel updates a single label
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLabels(self, request, context):
        """ListLabels lists all labels for a given organization
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLabel(self, request, context):
        """DeleteLabel deletes a single label
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AttachLabel(self, request, context):
        """AttachLabel attaches a label to a given entity type
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetachLabel(self, request, context):
        """DetachLabel detaches a label from an entity based on an entity type
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLabeledEntityMap(self, request, context):
        """GetLabeledEntityMap gives back a map of entity Id to attached labels. The Entity type is specified on the request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignLabels(self, request, context):
        """AssignLabels assigns labels to a specific permission group.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeLabels(self, request, context):
        """RevokeLabels revokes labels from a specific permission group.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LabelsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateLabel': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLabel,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.CreateLabelRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.CreateLabelResponse.SerializeToString,
            ),
            'GetLabel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLabel,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.GetLabelRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.GetLabelResponse.SerializeToString,
            ),
            'UpdateLabel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLabel,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.UpdateLabelRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.UpdateLabelResponse.SerializeToString,
            ),
            'ListLabels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLabels,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.ListLabelsRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.ListLabelsResponse.SerializeToString,
            ),
            'DeleteLabel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLabel,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.DeleteLabelRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.DeleteLabelResponse.SerializeToString,
            ),
            'AttachLabel': grpc.unary_unary_rpc_method_handler(
                    servicer.AttachLabel,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.AttachLabelRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.AttachLabelResponse.SerializeToString,
            ),
            'DetachLabel': grpc.unary_unary_rpc_method_handler(
                    servicer.DetachLabel,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.DetachLabelRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.DetachLabelResponse.SerializeToString,
            ),
            'GetLabeledEntityMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLabeledEntityMap,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.GetLabeledEntityMapRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.GetLabeledEntityMapResponse.SerializeToString,
            ),
            'AssignLabels': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignLabels,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.AssignLabelsRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.AssignLabelsResponse.SerializeToString,
            ),
            'RevokeLabels': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeLabels,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.RevokeLabelsRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.RevokeLabelsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1alpha1.org.labels.LabelsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LabelsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateLabel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.org.labels.LabelsService/CreateLabel',
            api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.CreateLabelRequest.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.CreateLabelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLabel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.org.labels.LabelsService/GetLabel',
            api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.GetLabelRequest.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.GetLabelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateLabel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.org.labels.LabelsService/UpdateLabel',
            api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.UpdateLabelRequest.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.UpdateLabelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListLabels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.org.labels.LabelsService/ListLabels',
            api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.ListLabelsRequest.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.ListLabelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteLabel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.org.labels.LabelsService/DeleteLabel',
            api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.DeleteLabelRequest.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.DeleteLabelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AttachLabel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.org.labels.LabelsService/AttachLabel',
            api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.AttachLabelRequest.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.AttachLabelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DetachLabel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.org.labels.LabelsService/DetachLabel',
            api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.DetachLabelRequest.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.DetachLabelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLabeledEntityMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.org.labels.LabelsService/GetLabeledEntityMap',
            api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.GetLabeledEntityMapRequest.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.GetLabeledEntityMapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AssignLabels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.org.labels.LabelsService/AssignLabels',
            api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.AssignLabelsRequest.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.AssignLabelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RevokeLabels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.org.labels.LabelsService/RevokeLabels',
            api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.RevokeLabelsRequest.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_labels_dot_entities__pb2.RevokeLabelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
