# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1alpha1/workflows/nodes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.v1alpha1.workflows import omni_pb2 as api_dot_v1alpha1_dot_workflows_dot_omni__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"api/v1alpha1/workflows/nodes.proto\x12\x16\x61pi.v1alpha1.workflows\x1a!api/v1alpha1/workflows/omni.proto\"\xda\x03\n\x0eNodeDefinition\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\x12 \n\x0b\x64\x65scription\x18\x04 \x01(\tR\x0b\x64\x65scription\x12\x18\n\x07outputs\x18\x05 \x03(\tR\x07outputs\x12\"\n\rerror_node_id\x18\x06 \x01(\tR\x0b\x65rrorNodeId\x12J\n\x0bomni_prompt\x18\xc9\x01 \x01(\x0b\x32&.api.v1alpha1.workflows.OmniNodePromptH\x00R\nomniPrompt\x12Q\n\x0eomni_set_skill\x18\xca\x01 \x01(\x0b\x32(.api.v1alpha1.workflows.OmniNodeSetSkillH\x00R\x0comniSetSkill\x12N\n\romni_to_agent\x18\xcb\x01 \x01(\x0b\x32\'.api.v1alpha1.workflows.OmniNodeToAgentH\x00R\x0bomniToAgent\x12G\n\nomni_error\x18\xcc\x01 \x01(\x0b\x32%.api.v1alpha1.workflows.OmniNodeErrorH\x00R\tomniErrorB\x0c\n\ndefinitionB\xa2\x01\n\x1a\x63om.api.v1alpha1.workflowsB\nNodesProtoP\x01\xa2\x02\x03\x41VW\xaa\x02\x16\x41pi.V1alpha1.Workflows\xca\x02\x16\x41pi\\V1alpha1\\Workflows\xe2\x02\"Api\\V1alpha1\\Workflows\\GPBMetadata\xea\x02\x18\x41pi::V1alpha1::Workflowsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1alpha1.workflows.nodes_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.api.v1alpha1.workflowsB\nNodesProtoP\001\242\002\003AVW\252\002\026Api.V1alpha1.Workflows\312\002\026Api\\V1alpha1\\Workflows\342\002\"Api\\V1alpha1\\Workflows\\GPBMetadata\352\002\030Api::V1alpha1::Workflows'
  _globals['_NODEDEFINITION']._serialized_start=98
  _globals['_NODEDEFINITION']._serialized_end=572
# @@protoc_insertion_point(module_scope)
