# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1alpha1/workflows/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from annotations import authz_pb2 as annotations_dot_authz__pb2
from api.v1alpha1.workflows import entities_pb2 as api_dot_v1alpha1_dot_workflows_dot_entities__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$api/v1alpha1/workflows/service.proto\x12\x16\x61pi.v1alpha1.workflows\x1a\x17\x61nnotations/authz.proto\x1a%api/v1alpha1/workflows/entities.proto\x1a\x1cgoogle/api/annotations.proto2\xa0\x06\n\x1aWorkflowsDefinitionService\x12\xc0\x01\n\x13ListFlowDefinitions\x12\x32.api.v1alpha1.workflows.ListFlowDefinitionsRequest\x1a\x33.api.v1alpha1.workflows.ListFlowDefinitionsResponse\"@\xba\xb8\x91\x02\x05\n\x03\x08\xa0\x1f\x82\xd3\xe4\x93\x02\x30\"+/api/v1alpha1/workflows/listflowdefinitions:\x01*\x12\xbc\x01\n\x12SaveFlowDefinition\x12\x31.api.v1alpha1.workflows.SaveFlowDefinitionRequest\x1a\x32.api.v1alpha1.workflows.SaveFlowDefinitionResponse\"?\xba\xb8\x91\x02\x05\n\x03\x08\xa0\x1f\x82\xd3\xe4\x93\x02/\"*/api/v1alpha1/workflows/saveflowdefinition:\x01*\x12\xb8\x01\n\x11GetFlowDefinition\x12\x30.api.v1alpha1.workflows.GetFlowDefinitionRequest\x1a\x31.api.v1alpha1.workflows.GetFlowDefinitionResponse\">\xba\xb8\x91\x02\x05\n\x03\x08\xa0\x1f\x82\xd3\xe4\x93\x02.\")/api/v1alpha1/workflows/getflowdefinition:\x01*\x12\xc4\x01\n\x14\x44\x65leteFlowDefinition\x12\x33.api.v1alpha1.workflows.DeleteFlowDefinitionRequest\x1a\x34.api.v1alpha1.workflows.DeleteFlowDefinitionResponse\"A\xba\xb8\x91\x02\x05\n\x03\x08\xa0\x1f\x82\xd3\xe4\x93\x02\x31\",/api/v1alpha1/workflows/deleteflowdefinition:\x01*B\xa4\x01\n\x1a\x63om.api.v1alpha1.workflowsB\x0cServiceProtoP\x01\xa2\x02\x03\x41VW\xaa\x02\x16\x41pi.V1alpha1.Workflows\xca\x02\x16\x41pi\\V1alpha1\\Workflows\xe2\x02\"Api\\V1alpha1\\Workflows\\GPBMetadata\xea\x02\x18\x41pi::V1alpha1::Workflowsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1alpha1.workflows.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.api.v1alpha1.workflowsB\014ServiceProtoP\001\242\002\003AVW\252\002\026Api.V1alpha1.Workflows\312\002\026Api\\V1alpha1\\Workflows\342\002\"Api\\V1alpha1\\Workflows\\GPBMetadata\352\002\030Api::V1alpha1::Workflows'
  _WORKFLOWSDEFINITIONSERVICE.methods_by_name['ListFlowDefinitions']._options = None
  _WORKFLOWSDEFINITIONSERVICE.methods_by_name['ListFlowDefinitions']._serialized_options = b'\272\270\221\002\005\n\003\010\240\037\202\323\344\223\0020\"+/api/v1alpha1/workflows/listflowdefinitions:\001*'
  _WORKFLOWSDEFINITIONSERVICE.methods_by_name['SaveFlowDefinition']._options = None
  _WORKFLOWSDEFINITIONSERVICE.methods_by_name['SaveFlowDefinition']._serialized_options = b'\272\270\221\002\005\n\003\010\240\037\202\323\344\223\002/\"*/api/v1alpha1/workflows/saveflowdefinition:\001*'
  _WORKFLOWSDEFINITIONSERVICE.methods_by_name['GetFlowDefinition']._options = None
  _WORKFLOWSDEFINITIONSERVICE.methods_by_name['GetFlowDefinition']._serialized_options = b'\272\270\221\002\005\n\003\010\240\037\202\323\344\223\002.\")/api/v1alpha1/workflows/getflowdefinition:\001*'
  _WORKFLOWSDEFINITIONSERVICE.methods_by_name['DeleteFlowDefinition']._options = None
  _WORKFLOWSDEFINITIONSERVICE.methods_by_name['DeleteFlowDefinition']._serialized_options = b'\272\270\221\002\005\n\003\010\240\037\202\323\344\223\0021\",/api/v1alpha1/workflows/deleteflowdefinition:\001*'
  _globals['_WORKFLOWSDEFINITIONSERVICE']._serialized_start=159
  _globals['_WORKFLOWSDEFINITIONSERVICE']._serialized_end=959
# @@protoc_insertion_point(module_scope)
