# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.v1alpha1.workflows import service_pb2 as api_dot_v1alpha1_dot_workflows_dot_service__pb2


class FlowDefinitionPersistServiceStub(object):
    """FlowDefinitionPersistService is the service that provides CRUD operations for FlowDefinitions.
    PERMISSION_WORKFLOWS is required for all operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateFlowDefinition = channel.unary_unary(
                '/api.v1alpha1.workflows.FlowDefinitionPersistService/CreateFlowDefinition',
                request_serializer=api_dot_v1alpha1_dot_workflows_dot_service__pb2.CreateFlowDefinitionRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_workflows_dot_service__pb2.CreateFlowDefinitionResponse.FromString,
                )
        self.GetFlowDefinition = channel.unary_unary(
                '/api.v1alpha1.workflows.FlowDefinitionPersistService/GetFlowDefinition',
                request_serializer=api_dot_v1alpha1_dot_workflows_dot_service__pb2.GetFlowDefinitionRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_workflows_dot_service__pb2.GetFlowDefinitionResponse.FromString,
                )
        self.ListFlowDefinitions = channel.unary_stream(
                '/api.v1alpha1.workflows.FlowDefinitionPersistService/ListFlowDefinitions',
                request_serializer=api_dot_v1alpha1_dot_workflows_dot_service__pb2.ListFlowDefinitionsRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_workflows_dot_service__pb2.ListFlowDefinitionsResponse.FromString,
                )
        self.UpdateFlowDefinition = channel.unary_unary(
                '/api.v1alpha1.workflows.FlowDefinitionPersistService/UpdateFlowDefinition',
                request_serializer=api_dot_v1alpha1_dot_workflows_dot_service__pb2.UpdateFlowDefinitionRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_workflows_dot_service__pb2.UpdateFlowDefinitionResponse.FromString,
                )
        self.ValidateFlowDefinition = channel.unary_unary(
                '/api.v1alpha1.workflows.FlowDefinitionPersistService/ValidateFlowDefinition',
                request_serializer=api_dot_v1alpha1_dot_workflows_dot_service__pb2.ValidateFlowDefinitionRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_workflows_dot_service__pb2.ValidateFlowDefinitionResponse.FromString,
                )


class FlowDefinitionPersistServiceServicer(object):
    """FlowDefinitionPersistService is the service that provides CRUD operations for FlowDefinitions.
    PERMISSION_WORKFLOWS is required for all operations
    """

    def CreateFlowDefinition(self, request, context):
        """CreateFlowDefinition creates a new flow definition in the database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFlowDefinition(self, request, context):
        """GetFlowDefinition retrieves a flow definition from the database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFlowDefinitions(self, request, context):
        """ListFlowDefinitions retrieves a list of flow definitions from the database optionally filtered by the owning application
        if application is not specified, all flow definitions for the org are returned
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFlowDefinition(self, request, context):
        """UpdateFlowDefinition updates a flow definition in the database. Only the name, description and definition graph itself are updated
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateFlowDefinition(self, request, context):
        """ValidateFlowDefinition validates a flow definition in the database. Only the name, description and definition graph itself are updated
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlowDefinitionPersistServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateFlowDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFlowDefinition,
                    request_deserializer=api_dot_v1alpha1_dot_workflows_dot_service__pb2.CreateFlowDefinitionRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_workflows_dot_service__pb2.CreateFlowDefinitionResponse.SerializeToString,
            ),
            'GetFlowDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFlowDefinition,
                    request_deserializer=api_dot_v1alpha1_dot_workflows_dot_service__pb2.GetFlowDefinitionRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_workflows_dot_service__pb2.GetFlowDefinitionResponse.SerializeToString,
            ),
            'ListFlowDefinitions': grpc.unary_stream_rpc_method_handler(
                    servicer.ListFlowDefinitions,
                    request_deserializer=api_dot_v1alpha1_dot_workflows_dot_service__pb2.ListFlowDefinitionsRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_workflows_dot_service__pb2.ListFlowDefinitionsResponse.SerializeToString,
            ),
            'UpdateFlowDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFlowDefinition,
                    request_deserializer=api_dot_v1alpha1_dot_workflows_dot_service__pb2.UpdateFlowDefinitionRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_workflows_dot_service__pb2.UpdateFlowDefinitionResponse.SerializeToString,
            ),
            'ValidateFlowDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateFlowDefinition,
                    request_deserializer=api_dot_v1alpha1_dot_workflows_dot_service__pb2.ValidateFlowDefinitionRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_workflows_dot_service__pb2.ValidateFlowDefinitionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1alpha1.workflows.FlowDefinitionPersistService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FlowDefinitionPersistService(object):
    """FlowDefinitionPersistService is the service that provides CRUD operations for FlowDefinitions.
    PERMISSION_WORKFLOWS is required for all operations
    """

    @staticmethod
    def CreateFlowDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.workflows.FlowDefinitionPersistService/CreateFlowDefinition',
            api_dot_v1alpha1_dot_workflows_dot_service__pb2.CreateFlowDefinitionRequest.SerializeToString,
            api_dot_v1alpha1_dot_workflows_dot_service__pb2.CreateFlowDefinitionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFlowDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.workflows.FlowDefinitionPersistService/GetFlowDefinition',
            api_dot_v1alpha1_dot_workflows_dot_service__pb2.GetFlowDefinitionRequest.SerializeToString,
            api_dot_v1alpha1_dot_workflows_dot_service__pb2.GetFlowDefinitionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListFlowDefinitions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/api.v1alpha1.workflows.FlowDefinitionPersistService/ListFlowDefinitions',
            api_dot_v1alpha1_dot_workflows_dot_service__pb2.ListFlowDefinitionsRequest.SerializeToString,
            api_dot_v1alpha1_dot_workflows_dot_service__pb2.ListFlowDefinitionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateFlowDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.workflows.FlowDefinitionPersistService/UpdateFlowDefinition',
            api_dot_v1alpha1_dot_workflows_dot_service__pb2.UpdateFlowDefinitionRequest.SerializeToString,
            api_dot_v1alpha1_dot_workflows_dot_service__pb2.UpdateFlowDefinitionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ValidateFlowDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.workflows.FlowDefinitionPersistService/ValidateFlowDefinition',
            api_dot_v1alpha1_dot_workflows_dot_service__pb2.ValidateFlowDefinitionRequest.SerializeToString,
            api_dot_v1alpha1_dot_workflows_dot_service__pb2.ValidateFlowDefinitionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
