# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.v1alpha1.newsroom import entities_pb2 as api_dot_v1alpha1_dot_newsroom_dot_entities__pb2


class NewsroomAPIStub(object):
    """Service for interacting with TCN's Newsroom API system.
    Accessing all of the methods Requestuire an authenticated user with the correct
    permissions.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNewsArticle = channel.unary_unary(
                '/api.v1alpha1.newsroom.NewsroomAPI/CreateNewsArticle',
                request_serializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.CreateNewsArticleRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.CreateNewsArticleResponse.FromString,
                )
        self.ListNewsArticles = channel.unary_unary(
                '/api.v1alpha1.newsroom.NewsroomAPI/ListNewsArticles',
                request_serializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.ListNewsArticlesRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.ListNewsArticlesResponse.FromString,
                )
        self.GetNewsArticleById = channel.unary_unary(
                '/api.v1alpha1.newsroom.NewsroomAPI/GetNewsArticleById',
                request_serializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.GetNewsArticleByIdRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.GetNewsArticleByIdResponse.FromString,
                )
        self.UpdateNewsArticle = channel.unary_unary(
                '/api.v1alpha1.newsroom.NewsroomAPI/UpdateNewsArticle',
                request_serializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.UpdateNewsArticleRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.UpdateNewsArticleResponse.FromString,
                )
        self.CreatePublishedArticle = channel.unary_unary(
                '/api.v1alpha1.newsroom.NewsroomAPI/CreatePublishedArticle',
                request_serializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.CreatePublishedArticleRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.CreatePublishedArticleResponse.FromString,
                )
        self.ListPublishedArticles = channel.unary_unary(
                '/api.v1alpha1.newsroom.NewsroomAPI/ListPublishedArticles',
                request_serializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.ListPublishedArticlesRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.ListPublishedArticlesResponse.FromString,
                )
        self.GetPublishedArticleById = channel.unary_unary(
                '/api.v1alpha1.newsroom.NewsroomAPI/GetPublishedArticleById',
                request_serializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.GetPublishedArticleByIdRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.GetPublishedArticleByIdResponse.FromString,
                )
        self.UserActivity = channel.unary_unary(
                '/api.v1alpha1.newsroom.NewsroomAPI/UserActivity',
                request_serializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.UserActivityRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.UserActivityResponse.FromString,
                )
        self.GetNewsForUser = channel.unary_unary(
                '/api.v1alpha1.newsroom.NewsroomAPI/GetNewsForUser',
                request_serializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.GetNewsForUserRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.GetNewsForUserResponse.FromString,
                )


class NewsroomAPIServicer(object):
    """Service for interacting with TCN's Newsroom API system.
    Accessing all of the methods Requestuire an authenticated user with the correct
    permissions.
    """

    def CreateNewsArticle(self, request, context):
        """create news article
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNewsArticles(self, request, context):
        """list news articles
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNewsArticleById(self, request, context):
        """get news article details by the id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNewsArticle(self, request, context):
        """update news article
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePublishedArticle(self, request, context):
        """create published article
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPublishedArticles(self, request, context):
        """list published articles
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPublishedArticleById(self, request, context):
        """get published article details by the id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserActivity(self, request, context):
        """user activity updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNewsForUser(self, request, context):
        """fetch the unseen articles for the user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NewsroomAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNewsArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNewsArticle,
                    request_deserializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.CreateNewsArticleRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.CreateNewsArticleResponse.SerializeToString,
            ),
            'ListNewsArticles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNewsArticles,
                    request_deserializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.ListNewsArticlesRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.ListNewsArticlesResponse.SerializeToString,
            ),
            'GetNewsArticleById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNewsArticleById,
                    request_deserializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.GetNewsArticleByIdRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.GetNewsArticleByIdResponse.SerializeToString,
            ),
            'UpdateNewsArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNewsArticle,
                    request_deserializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.UpdateNewsArticleRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.UpdateNewsArticleResponse.SerializeToString,
            ),
            'CreatePublishedArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePublishedArticle,
                    request_deserializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.CreatePublishedArticleRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.CreatePublishedArticleResponse.SerializeToString,
            ),
            'ListPublishedArticles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPublishedArticles,
                    request_deserializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.ListPublishedArticlesRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.ListPublishedArticlesResponse.SerializeToString,
            ),
            'GetPublishedArticleById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublishedArticleById,
                    request_deserializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.GetPublishedArticleByIdRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.GetPublishedArticleByIdResponse.SerializeToString,
            ),
            'UserActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.UserActivity,
                    request_deserializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.UserActivityRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.UserActivityResponse.SerializeToString,
            ),
            'GetNewsForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNewsForUser,
                    request_deserializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.GetNewsForUserRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.GetNewsForUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1alpha1.newsroom.NewsroomAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NewsroomAPI(object):
    """Service for interacting with TCN's Newsroom API system.
    Accessing all of the methods Requestuire an authenticated user with the correct
    permissions.
    """

    @staticmethod
    def CreateNewsArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.newsroom.NewsroomAPI/CreateNewsArticle',
            api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.CreateNewsArticleRequest.SerializeToString,
            api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.CreateNewsArticleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListNewsArticles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.newsroom.NewsroomAPI/ListNewsArticles',
            api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.ListNewsArticlesRequest.SerializeToString,
            api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.ListNewsArticlesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNewsArticleById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.newsroom.NewsroomAPI/GetNewsArticleById',
            api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.GetNewsArticleByIdRequest.SerializeToString,
            api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.GetNewsArticleByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateNewsArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.newsroom.NewsroomAPI/UpdateNewsArticle',
            api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.UpdateNewsArticleRequest.SerializeToString,
            api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.UpdateNewsArticleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePublishedArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.newsroom.NewsroomAPI/CreatePublishedArticle',
            api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.CreatePublishedArticleRequest.SerializeToString,
            api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.CreatePublishedArticleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListPublishedArticles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.newsroom.NewsroomAPI/ListPublishedArticles',
            api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.ListPublishedArticlesRequest.SerializeToString,
            api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.ListPublishedArticlesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPublishedArticleById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.newsroom.NewsroomAPI/GetPublishedArticleById',
            api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.GetPublishedArticleByIdRequest.SerializeToString,
            api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.GetPublishedArticleByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UserActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.newsroom.NewsroomAPI/UserActivity',
            api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.UserActivityRequest.SerializeToString,
            api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.UserActivityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNewsForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.newsroom.NewsroomAPI/GetNewsForUser',
            api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.GetNewsForUserRequest.SerializeToString,
            api_dot_v1alpha1_dot_newsroom_dot_entities__pb2.GetNewsForUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
