# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1alpha1/newsroom/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from annotations import authz_pb2 as annotations_dot_authz__pb2
from api.v1alpha1.newsroom import entities_pb2 as api_dot_v1alpha1_dot_newsroom_dot_entities__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#api/v1alpha1/newsroom/service.proto\x12\x15\x61pi.v1alpha1.newsroom\x1a\x17\x61nnotations/authz.proto\x1a$api/v1alpha1/newsroom/entities.proto\x1a\x1cgoogle/api/annotations.proto2U\n\x0bNewsroomAPI\x12\x46\n\x04Ping\x12\x1e.api.v1alpha1.newsroom.PingReq\x1a\x1e.api.v1alpha1.newsroom.PingResB\x9f\x01\n\x19\x63om.api.v1alpha1.newsroomB\x0cServiceProtoP\x01\xa2\x02\x03\x41VN\xaa\x02\x15\x41pi.V1alpha1.Newsroom\xca\x02\x15\x41pi\\V1alpha1\\Newsroom\xe2\x02!Api\\V1alpha1\\Newsroom\\GPBMetadata\xea\x02\x17\x41pi::V1alpha1::Newsroomb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1alpha1.newsroom.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031com.api.v1alpha1.newsroomB\014ServiceProtoP\001\242\002\003AVN\252\002\025Api.V1alpha1.Newsroom\312\002\025Api\\V1alpha1\\Newsroom\342\002!Api\\V1alpha1\\Newsroom\\GPBMetadata\352\002\027Api::V1alpha1::Newsroom'
  _globals['_NEWSROOMAPI']._serialized_start=155
  _globals['_NEWSROOMAPI']._serialized_end=240
# @@protoc_insertion_point(module_scope)
