# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.v1alpha1.org.soundboard import entities_pb2 as api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2


class SoundboardStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSoundboardFile = channel.unary_stream(
                '/api.v1alpha1.soundboard.Soundboard/GetSoundboardFile',
                request_serializer=api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.GetSoundboardFileReq.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.GetSoundboardFileRes.FromString,
                )
        self.CreateSoundboard = channel.unary_unary(
                '/api.v1alpha1.soundboard.Soundboard/CreateSoundboard',
                request_serializer=api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.CreateSoundboardReq.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.CreateSoundboardRes.FromString,
                )
        self.ListSoundboards = channel.unary_unary(
                '/api.v1alpha1.soundboard.Soundboard/ListSoundboards',
                request_serializer=api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.ListSoundboardsReq.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.ListSoundboardsRes.FromString,
                )
        self.UpdateSoundboard = channel.unary_unary(
                '/api.v1alpha1.soundboard.Soundboard/UpdateSoundboard',
                request_serializer=api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.UpdateSoundboardReq.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.UpdateSoundboardRes.FromString,
                )
        self.DeleteSoundboard = channel.unary_unary(
                '/api.v1alpha1.soundboard.Soundboard/DeleteSoundboard',
                request_serializer=api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.DeleteSoundboardReq.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.DeleteSoundboardRes.FromString,
                )


class SoundboardServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSoundboardFile(self, request, context):
        """GetSoundboardFile streams back segments of the audio file stored in rec
        corresponding to the provided soundboard id and org id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSoundboard(self, request, context):
        """CreateSoundboard takes in a stream of metadata and audio file segments.
        The first expected message should contain SoundboardDetails, then following
        messages will be chunks of audio file data, which is then aggregated and put
        into rec. The generated soundboard id is returned.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSoundboards(self, request, context):
        """ListSoundboards returns all of the metadata for soundboards corresponding
        corresponding to a given org id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSoundboard(self, request, context):
        """UpdateSondboard updates a soundboard's metadata in the soundboard table.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSoundboard(self, request, context):
        """DeleteSondboard deletes a soundboard's metadata from the soundboard table.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SoundboardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSoundboardFile': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSoundboardFile,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.GetSoundboardFileReq.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.GetSoundboardFileRes.SerializeToString,
            ),
            'CreateSoundboard': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSoundboard,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.CreateSoundboardReq.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.CreateSoundboardRes.SerializeToString,
            ),
            'ListSoundboards': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSoundboards,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.ListSoundboardsReq.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.ListSoundboardsRes.SerializeToString,
            ),
            'UpdateSoundboard': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSoundboard,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.UpdateSoundboardReq.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.UpdateSoundboardRes.SerializeToString,
            ),
            'DeleteSoundboard': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSoundboard,
                    request_deserializer=api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.DeleteSoundboardReq.FromString,
                    response_serializer=api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.DeleteSoundboardRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1alpha1.soundboard.Soundboard', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Soundboard(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSoundboardFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/api.v1alpha1.soundboard.Soundboard/GetSoundboardFile',
            api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.GetSoundboardFileReq.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.GetSoundboardFileRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateSoundboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.soundboard.Soundboard/CreateSoundboard',
            api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.CreateSoundboardReq.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.CreateSoundboardRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSoundboards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.soundboard.Soundboard/ListSoundboards',
            api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.ListSoundboardsReq.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.ListSoundboardsRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateSoundboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.soundboard.Soundboard/UpdateSoundboard',
            api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.UpdateSoundboardReq.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.UpdateSoundboardRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSoundboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.soundboard.Soundboard/DeleteSoundboard',
            api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.DeleteSoundboardReq.SerializeToString,
            api_dot_v1alpha1_dot_org_dot_soundboard_dot_entities__pb2.DeleteSoundboardRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
