# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1alpha1/soundboard/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from annotations import authz_pb2 as annotations_dot_authz__pb2
from api.v1alpha1.soundboard import entities_pb2 as api_dot_v1alpha1_dot_soundboard_dot_entities__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%api/v1alpha1/soundboard/service.proto\x12\x17\x61pi.v1alpha1.soundboard\x1a\x17\x61nnotations/authz.proto\x1a&api/v1alpha1/soundboard/entities.proto\x1a\x1cgoogle/api/annotations.proto2\xba\x07\n\nSoundboard\x12\xbf\x01\n\x11GetSoundboardFile\x12-.api.v1alpha1.soundboard.GetSoundboardFileReq\x1a-.api.v1alpha1.soundboard.GetSoundboardFileRes\"J\xba\xb8\x91\x02\x05\n\x03\x08\xa4\r\x82\xd3\xe4\x93\x02:\"5/api/v1alpha1/soundboard/soundboard/getsoundboardfile:\x01*0\x01\x12\xb9\x01\n\x10\x43reateSoundboard\x12,.api.v1alpha1.soundboard.CreateSoundboardReq\x1a,.api.v1alpha1.soundboard.CreateSoundboardRes\"I\xba\xb8\x91\x02\x05\n\x03\x08\xa5\r\x82\xd3\xe4\x93\x02\x39\"4/api/v1alpha1/soundboard/soundboard/createsoundboard:\x01*\x12\xb5\x01\n\x0fListSoundboards\x12+.api.v1alpha1.soundboard.ListSoundboardsReq\x1a+.api.v1alpha1.soundboard.ListSoundboardsRes\"H\xba\xb8\x91\x02\x05\n\x03\x08\xa4\r\x82\xd3\xe4\x93\x02\x38\"3/api/v1alpha1/soundboard/soundboard/listsoundboards:\x01*\x12\xb9\x01\n\x10UpdateSoundboard\x12,.api.v1alpha1.soundboard.UpdateSoundboardReq\x1a,.api.v1alpha1.soundboard.UpdateSoundboardRes\"I\xba\xb8\x91\x02\x05\n\x03\x08\xa5\r\x82\xd3\xe4\x93\x02\x39\"4/api/v1alpha1/soundboard/soundboard/updatesoundboard:\x01*\x12\xb9\x01\n\x10\x44\x65leteSoundboard\x12,.api.v1alpha1.soundboard.DeleteSoundboardReq\x1a,.api.v1alpha1.soundboard.DeleteSoundboardRes\"I\xba\xb8\x91\x02\x05\n\x03\x08\xa5\r\x82\xd3\xe4\x93\x02\x39\"4/api/v1alpha1/soundboard/soundboard/deletesoundboard:\x01*B\xa9\x01\n\x1b\x63om.api.v1alpha1.soundboardB\x0cServiceProtoP\x01\xa2\x02\x03\x41VS\xaa\x02\x17\x41pi.V1alpha1.Soundboard\xca\x02\x17\x41pi\\V1alpha1\\Soundboard\xe2\x02#Api\\V1alpha1\\Soundboard\\GPBMetadata\xea\x02\x19\x41pi::V1alpha1::Soundboardb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1alpha1.soundboard.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033com.api.v1alpha1.soundboardB\014ServiceProtoP\001\242\002\003AVS\252\002\027Api.V1alpha1.Soundboard\312\002\027Api\\V1alpha1\\Soundboard\342\002#Api\\V1alpha1\\Soundboard\\GPBMetadata\352\002\031Api::V1alpha1::Soundboard'
  _SOUNDBOARD.methods_by_name['GetSoundboardFile']._options = None
  _SOUNDBOARD.methods_by_name['GetSoundboardFile']._serialized_options = b'\272\270\221\002\005\n\003\010\244\r\202\323\344\223\002:\"5/api/v1alpha1/soundboard/soundboard/getsoundboardfile:\001*'
  _SOUNDBOARD.methods_by_name['CreateSoundboard']._options = None
  _SOUNDBOARD.methods_by_name['CreateSoundboard']._serialized_options = b'\272\270\221\002\005\n\003\010\245\r\202\323\344\223\0029\"4/api/v1alpha1/soundboard/soundboard/createsoundboard:\001*'
  _SOUNDBOARD.methods_by_name['ListSoundboards']._options = None
  _SOUNDBOARD.methods_by_name['ListSoundboards']._serialized_options = b'\272\270\221\002\005\n\003\010\244\r\202\323\344\223\0028\"3/api/v1alpha1/soundboard/soundboard/listsoundboards:\001*'
  _SOUNDBOARD.methods_by_name['UpdateSoundboard']._options = None
  _SOUNDBOARD.methods_by_name['UpdateSoundboard']._serialized_options = b'\272\270\221\002\005\n\003\010\245\r\202\323\344\223\0029\"4/api/v1alpha1/soundboard/soundboard/updatesoundboard:\001*'
  _SOUNDBOARD.methods_by_name['DeleteSoundboard']._options = None
  _SOUNDBOARD.methods_by_name['DeleteSoundboard']._serialized_options = b'\272\270\221\002\005\n\003\010\245\r\202\323\344\223\0029\"4/api/v1alpha1/soundboard/soundboard/deletesoundboard:\001*'
  _globals['_SOUNDBOARD']._serialized_start=162
  _globals['_SOUNDBOARD']._serialized_end=1116
# @@protoc_insertion_point(module_scope)
