# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/billing/entities/v1alpha3/matching.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'services/billing/entities/v1alpha3/matching.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1services/billing/entities/v1alpha3/matching.proto\x12\"services.billing.entities.v1alpha3\"R\n\x11\x43ountryCodePrefix\x12!\n\x0c\x63ountry_code\x18\x01 \x01(\x05R\x0b\x63ountryCode\x12\x1a\n\x08prefixes\x18\x02 \x03(\tR\x08prefixesB\xe2\x01\n&com.services.billing.entities.v1alpha3B\rMatchingProtoP\x01\xa2\x02\x03SBE\xaa\x02\"Services.Billing.Entities.V1alpha3\xca\x02\"Services\\Billing\\Entities\\V1alpha3\xe2\x02.Services\\Billing\\Entities\\V1alpha3\\GPBMetadata\xea\x02%Services::Billing::Entities::V1alpha3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.billing.entities.v1alpha3.matching_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n&com.services.billing.entities.v1alpha3B\rMatchingProtoP\001\242\002\003SBE\252\002\"Services.Billing.Entities.V1alpha3\312\002\"Services\\Billing\\Entities\\V1alpha3\342\002.Services\\Billing\\Entities\\V1alpha3\\GPBMetadata\352\002%Services::Billing::Entities::V1alpha3'
  _globals['_COUNTRYCODEPREFIX']._serialized_start=89
  _globals['_COUNTRYCODEPREFIX']._serialized_end=171
# @@protoc_insertion_point(module_scope)
