# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.v1alpha1.billing import entities_pb2 as api_dot_v1alpha1_dot_billing_dot_entities__pb2


class BillingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBillingPlan = channel.unary_unary(
                '/api.v1alpha1.billing.Billing/GetBillingPlan',
                request_serializer=api_dot_v1alpha1_dot_billing_dot_entities__pb2.GetBillingPlanReq.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_billing_dot_entities__pb2.GetBillingPlanRes.FromString,
                )
        self.UpdateBillingPlan = channel.unary_unary(
                '/api.v1alpha1.billing.Billing/UpdateBillingPlan',
                request_serializer=api_dot_v1alpha1_dot_billing_dot_entities__pb2.UpdateBillingPlanReq.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_billing_dot_entities__pb2.UpdateBillingPlanRes.FromString,
                )
        self.GetInvoice = channel.unary_unary(
                '/api.v1alpha1.billing.Billing/GetInvoice',
                request_serializer=api_dot_v1alpha1_dot_billing_dot_entities__pb2.GetInvoiceReq.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_billing_dot_entities__pb2.GetInvoiceRes.FromString,
                )
        self.ExportGeneratedInvoice = channel.unary_unary(
                '/api.v1alpha1.billing.Billing/ExportGeneratedInvoice',
                request_serializer=api_dot_v1alpha1_dot_billing_dot_entities__pb2.ExportGeneratedInvoiceReq.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_billing_dot_entities__pb2.ExportGeneratedInvoiceRes.FromString,
                )


class BillingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBillingPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBillingPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInvoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportGeneratedInvoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BillingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBillingPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBillingPlan,
                    request_deserializer=api_dot_v1alpha1_dot_billing_dot_entities__pb2.GetBillingPlanReq.FromString,
                    response_serializer=api_dot_v1alpha1_dot_billing_dot_entities__pb2.GetBillingPlanRes.SerializeToString,
            ),
            'UpdateBillingPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBillingPlan,
                    request_deserializer=api_dot_v1alpha1_dot_billing_dot_entities__pb2.UpdateBillingPlanReq.FromString,
                    response_serializer=api_dot_v1alpha1_dot_billing_dot_entities__pb2.UpdateBillingPlanRes.SerializeToString,
            ),
            'GetInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInvoice,
                    request_deserializer=api_dot_v1alpha1_dot_billing_dot_entities__pb2.GetInvoiceReq.FromString,
                    response_serializer=api_dot_v1alpha1_dot_billing_dot_entities__pb2.GetInvoiceRes.SerializeToString,
            ),
            'ExportGeneratedInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportGeneratedInvoice,
                    request_deserializer=api_dot_v1alpha1_dot_billing_dot_entities__pb2.ExportGeneratedInvoiceReq.FromString,
                    response_serializer=api_dot_v1alpha1_dot_billing_dot_entities__pb2.ExportGeneratedInvoiceRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1alpha1.billing.Billing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Billing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBillingPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.billing.Billing/GetBillingPlan',
            api_dot_v1alpha1_dot_billing_dot_entities__pb2.GetBillingPlanReq.SerializeToString,
            api_dot_v1alpha1_dot_billing_dot_entities__pb2.GetBillingPlanRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateBillingPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.billing.Billing/UpdateBillingPlan',
            api_dot_v1alpha1_dot_billing_dot_entities__pb2.UpdateBillingPlanReq.SerializeToString,
            api_dot_v1alpha1_dot_billing_dot_entities__pb2.UpdateBillingPlanRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.billing.Billing/GetInvoice',
            api_dot_v1alpha1_dot_billing_dot_entities__pb2.GetInvoiceReq.SerializeToString,
            api_dot_v1alpha1_dot_billing_dot_entities__pb2.GetInvoiceRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExportGeneratedInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.billing.Billing/ExportGeneratedInvoice',
            api_dot_v1alpha1_dot_billing_dot_entities__pb2.ExportGeneratedInvoiceReq.SerializeToString,
            api_dot_v1alpha1_dot_billing_dot_entities__pb2.ExportGeneratedInvoiceRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
