# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1alpha1/billing/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from annotations import authz_pb2 as annotations_dot_authz__pb2
from api.v1alpha1.billing import entities_pb2 as api_dot_v1alpha1_dot_billing_dot_entities__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"api/v1alpha1/billing/service.proto\x12\x14\x61pi.v1alpha1.billing\x1a\x17\x61nnotations/authz.proto\x1a#api/v1alpha1/billing/entities.proto\x1a\x1cgoogle/api/annotations.proto2\xd8\x06\n\x07\x42illing\x12\xac\x01\n\x11\x43reateBillingPlan\x12*.api.v1alpha1.billing.CreateBillingPlanReq\x1a*.api.v1alpha1.billing.CreateBillingPlanRes\"?\xba\xb8\x91\x02\x08\n\x06\x08\xc8\x01\x08\xdc\x01\x82\xd3\xe4\x93\x02,\"\'/api/v1alpha1/billing/createbillingplan:\x01*\x12\xa0\x01\n\x0eGetBillingPlan\x12\'.api.v1alpha1.billing.GetBillingPlanReq\x1a\'.api.v1alpha1.billing.GetBillingPlanRes\"<\xba\xb8\x91\x02\x08\n\x06\x08\xc8\x01\x08\xdc\x01\x82\xd3\xe4\x93\x02)\"$/api/v1alpha1/billing/getbillingplan:\x01*\x12\xac\x01\n\x11UpdateBillingPlan\x12*.api.v1alpha1.billing.UpdateBillingPlanReq\x1a*.api.v1alpha1.billing.UpdateBillingPlanRes\"?\xba\xb8\x91\x02\x08\n\x06\x08\xc8\x01\x08\xdc\x01\x82\xd3\xe4\x93\x02,\"\'/api/v1alpha1/billing/updatebillingplan:\x01*\x12\xb8\x01\n\x14\x44\x65leteBillingDetails\x12-.api.v1alpha1.billing.DeleteBillingDetailsReq\x1a-.api.v1alpha1.billing.DeleteBillingDetailsRes\"B\xba\xb8\x91\x02\x08\n\x06\x08\xc8\x01\x08\xdc\x01\x82\xd3\xe4\x93\x02/\"*/api/v1alpha1/billing/deletebillingdetails:\x01*\x12\x90\x01\n\nGetInvoice\x12#.api.v1alpha1.billing.GetInvoiceReq\x1a#.api.v1alpha1.billing.GetInvoiceRes\"8\xba\xb8\x91\x02\x08\n\x06\x08\xc8\x01\x08\xf0\x01\x82\xd3\xe4\x93\x02%\" /api/v1alpha1/billing/getinvoice:\x01*B\x9a\x01\n\x18\x63om.api.v1alpha1.billingB\x0cServiceProtoP\x01\xa2\x02\x03\x41VB\xaa\x02\x14\x41pi.V1alpha1.Billing\xca\x02\x14\x41pi\\V1alpha1\\Billing\xe2\x02 Api\\V1alpha1\\Billing\\GPBMetadata\xea\x02\x16\x41pi::V1alpha1::Billingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1alpha1.billing.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030com.api.v1alpha1.billingB\014ServiceProtoP\001\242\002\003AVB\252\002\024Api.V1alpha1.Billing\312\002\024Api\\V1alpha1\\Billing\342\002 Api\\V1alpha1\\Billing\\GPBMetadata\352\002\026Api::V1alpha1::Billing'
  _BILLING.methods_by_name['CreateBillingPlan']._options = None
  _BILLING.methods_by_name['CreateBillingPlan']._serialized_options = b'\272\270\221\002\010\n\006\010\310\001\010\334\001\202\323\344\223\002,\"\'/api/v1alpha1/billing/createbillingplan:\001*'
  _BILLING.methods_by_name['GetBillingPlan']._options = None
  _BILLING.methods_by_name['GetBillingPlan']._serialized_options = b'\272\270\221\002\010\n\006\010\310\001\010\334\001\202\323\344\223\002)\"$/api/v1alpha1/billing/getbillingplan:\001*'
  _BILLING.methods_by_name['UpdateBillingPlan']._options = None
  _BILLING.methods_by_name['UpdateBillingPlan']._serialized_options = b'\272\270\221\002\010\n\006\010\310\001\010\334\001\202\323\344\223\002,\"\'/api/v1alpha1/billing/updatebillingplan:\001*'
  _BILLING.methods_by_name['DeleteBillingDetails']._options = None
  _BILLING.methods_by_name['DeleteBillingDetails']._serialized_options = b'\272\270\221\002\010\n\006\010\310\001\010\334\001\202\323\344\223\002/\"*/api/v1alpha1/billing/deletebillingdetails:\001*'
  _BILLING.methods_by_name['GetInvoice']._options = None
  _BILLING.methods_by_name['GetInvoice']._serialized_options = b'\272\270\221\002\010\n\006\010\310\001\010\360\001\202\323\344\223\002%\" /api/v1alpha1/billing/getinvoice:\001*'
  _globals['_BILLING']._serialized_start=153
  _globals['_BILLING']._serialized_end=1009
# @@protoc_insertion_point(module_scope)
