# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.v1alpha1.lms import api_pb2 as api_dot_v1alpha1_dot_lms_dot_api__pb2


class LMSStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeleteFileTemplate = channel.unary_unary(
                '/api.v1alpha1.lms.LMS/DeleteFileTemplate',
                request_serializer=api_dot_v1alpha1_dot_lms_dot_api__pb2.DeleteFileTemplateRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_lms_dot_api__pb2.DeleteFileTemplateResponse.FromString,
                )
        self.GetFileTemplate = channel.unary_unary(
                '/api.v1alpha1.lms.LMS/GetFileTemplate',
                request_serializer=api_dot_v1alpha1_dot_lms_dot_api__pb2.GetFileTemplateRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_lms_dot_api__pb2.GetFileTemplateResponse.FromString,
                )
        self.ListFileTemplates = channel.unary_unary(
                '/api.v1alpha1.lms.LMS/ListFileTemplates',
                request_serializer=api_dot_v1alpha1_dot_lms_dot_api__pb2.ListFileTemplatesRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_lms_dot_api__pb2.ListFileTemplatesResponse.FromString,
                )
        self.ParseFileTemplate = channel.unary_unary(
                '/api.v1alpha1.lms.LMS/ParseFileTemplate',
                request_serializer=api_dot_v1alpha1_dot_lms_dot_api__pb2.ParseFileTemplateRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_lms_dot_api__pb2.ParseFileTemplateResult.FromString,
                )
        self.UpdateFileTemplate = channel.unary_unary(
                '/api.v1alpha1.lms.LMS/UpdateFileTemplate',
                request_serializer=api_dot_v1alpha1_dot_lms_dot_api__pb2.UpdateFileTemplateRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_lms_dot_api__pb2.UpdateFileTemplateResponse.FromString,
                )


class LMSServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DeleteFileTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFileTemplates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseFileTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFileTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LMSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeleteFileTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFileTemplate,
                    request_deserializer=api_dot_v1alpha1_dot_lms_dot_api__pb2.DeleteFileTemplateRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_lms_dot_api__pb2.DeleteFileTemplateResponse.SerializeToString,
            ),
            'GetFileTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileTemplate,
                    request_deserializer=api_dot_v1alpha1_dot_lms_dot_api__pb2.GetFileTemplateRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_lms_dot_api__pb2.GetFileTemplateResponse.SerializeToString,
            ),
            'ListFileTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFileTemplates,
                    request_deserializer=api_dot_v1alpha1_dot_lms_dot_api__pb2.ListFileTemplatesRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_lms_dot_api__pb2.ListFileTemplatesResponse.SerializeToString,
            ),
            'ParseFileTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseFileTemplate,
                    request_deserializer=api_dot_v1alpha1_dot_lms_dot_api__pb2.ParseFileTemplateRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_lms_dot_api__pb2.ParseFileTemplateResult.SerializeToString,
            ),
            'UpdateFileTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFileTemplate,
                    request_deserializer=api_dot_v1alpha1_dot_lms_dot_api__pb2.UpdateFileTemplateRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_lms_dot_api__pb2.UpdateFileTemplateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1alpha1.lms.LMS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LMS(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeleteFileTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.lms.LMS/DeleteFileTemplate',
            api_dot_v1alpha1_dot_lms_dot_api__pb2.DeleteFileTemplateRequest.SerializeToString,
            api_dot_v1alpha1_dot_lms_dot_api__pb2.DeleteFileTemplateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFileTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.lms.LMS/GetFileTemplate',
            api_dot_v1alpha1_dot_lms_dot_api__pb2.GetFileTemplateRequest.SerializeToString,
            api_dot_v1alpha1_dot_lms_dot_api__pb2.GetFileTemplateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListFileTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.lms.LMS/ListFileTemplates',
            api_dot_v1alpha1_dot_lms_dot_api__pb2.ListFileTemplatesRequest.SerializeToString,
            api_dot_v1alpha1_dot_lms_dot_api__pb2.ListFileTemplatesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ParseFileTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.lms.LMS/ParseFileTemplate',
            api_dot_v1alpha1_dot_lms_dot_api__pb2.ParseFileTemplateRequest.SerializeToString,
            api_dot_v1alpha1_dot_lms_dot_api__pb2.ParseFileTemplateResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateFileTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.lms.LMS/UpdateFileTemplate',
            api_dot_v1alpha1_dot_lms_dot_api__pb2.UpdateFileTemplateRequest.SerializeToString,
            api_dot_v1alpha1_dot_lms_dot_api__pb2.UpdateFileTemplateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
