# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.v1alpha1.contactmanager import contactmanager_pb2 as api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2


class ContactManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetContactList = channel.unary_unary(
                '/api.v1alpha1.contactmanager.ContactManager/GetContactList',
                request_serializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetContactListRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetContactListResponse.FromString,
                )
        self.ListContactEntryList = channel.unary_unary(
                '/api.v1alpha1.contactmanager.ContactManager/ListContactEntryList',
                request_serializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.ListContactEntryListRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.ListContactEntryListResponse.FromString,
                )
        self.GetEncContactEntry = channel.unary_unary(
                '/api.v1alpha1.contactmanager.ContactManager/GetEncContactEntry',
                request_serializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetEncContactEntryRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetEncContactEntryResponse.FromString,
                )
        self.GetKYCEncContactEntry = channel.unary_unary(
                '/api.v1alpha1.contactmanager.ContactManager/GetKYCEncContactEntry',
                request_serializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetKYCEncContactEntryRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetKYCEncContactEntryResponse.FromString,
                )
        self.GetKYCKeys = channel.unary_unary(
                '/api.v1alpha1.contactmanager.ContactManager/GetKYCKeys',
                request_serializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetKYCKeysRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetKYCKeysResponse.FromString,
                )
        self.AddContactEntry = channel.unary_unary(
                '/api.v1alpha1.contactmanager.ContactManager/AddContactEntry',
                request_serializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.AddContactEntryRequest.SerializeToString,
                response_deserializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.AddContactEntryResponse.FromString,
                )


class ContactManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetContactList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListContactEntryList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEncContactEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKYCEncContactEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKYCKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddContactEntry(self, request, context):
        """*
        Adds a new contact entry based on the provided request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContactManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetContactList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContactList,
                    request_deserializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetContactListRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetContactListResponse.SerializeToString,
            ),
            'ListContactEntryList': grpc.unary_unary_rpc_method_handler(
                    servicer.ListContactEntryList,
                    request_deserializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.ListContactEntryListRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.ListContactEntryListResponse.SerializeToString,
            ),
            'GetEncContactEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEncContactEntry,
                    request_deserializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetEncContactEntryRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetEncContactEntryResponse.SerializeToString,
            ),
            'GetKYCEncContactEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKYCEncContactEntry,
                    request_deserializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetKYCEncContactEntryRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetKYCEncContactEntryResponse.SerializeToString,
            ),
            'GetKYCKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKYCKeys,
                    request_deserializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetKYCKeysRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetKYCKeysResponse.SerializeToString,
            ),
            'AddContactEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.AddContactEntry,
                    request_deserializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.AddContactEntryRequest.FromString,
                    response_serializer=api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.AddContactEntryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1alpha1.contactmanager.ContactManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ContactManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetContactList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.contactmanager.ContactManager/GetContactList',
            api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetContactListRequest.SerializeToString,
            api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetContactListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListContactEntryList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.contactmanager.ContactManager/ListContactEntryList',
            api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.ListContactEntryListRequest.SerializeToString,
            api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.ListContactEntryListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEncContactEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.contactmanager.ContactManager/GetEncContactEntry',
            api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetEncContactEntryRequest.SerializeToString,
            api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetEncContactEntryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetKYCEncContactEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.contactmanager.ContactManager/GetKYCEncContactEntry',
            api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetKYCEncContactEntryRequest.SerializeToString,
            api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetKYCEncContactEntryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetKYCKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.contactmanager.ContactManager/GetKYCKeys',
            api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetKYCKeysRequest.SerializeToString,
            api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.GetKYCKeysResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddContactEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1alpha1.contactmanager.ContactManager/AddContactEntry',
            api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.AddContactEntryRequest.SerializeToString,
            api_dot_v1alpha1_dot_contactmanager_dot_contactmanager__pb2.AddContactEntryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
